fixed NoSuchMethodError (DoubleOption::getDisplayPrefix has protected access, returns always "options.gamma: ", now hardcoded in) changed the display text, now shows gamma.options.max when at 100% instead of 1200% improved toggle logic (dynamically checking if brightness is max, instead having a state, which could cause being stuck at max brightness; now using injection at MinecraftClient::tick instead of using deprecated ClientTickCallback.EVENT::register) added feature: reset to normal brightness before closing game